### ISSUE TITLE
Re-installs modules already installed in path from previous minor release

### ISSUE THREAD

**Issue by grr** [skaji/cpm#105]
I already had the latest `Log::Any` version installed in 5.26.0. Then I did a minor perl upgrade using perlbrew (`perlbrew upgrade-perl`) to update to 5.26.1. `@INC` includes both site_perl/5.26.0 and site_perl/5.26.1, but `cpm` didn't see the module was installed in site_perl/5.26.0, so it reinstalled it into site_perl/5.26.1. `cpanm` did however know that it was already installed.

    $ cpanm Log::Any
    Log::Any is up to date. (1.700)

    $ cpm install Log::Any
    DONE install Log-Any-1.700
    1 distribution installed.

    $ cd $perlhome/lib
    $ find . | grep Log/Any.pm
    ./site_perl/5.26.0/Log/Any.pm
    ./site_perl/5.26.1/Log/Any.pm

    $ ls -l ./site_perl/5.26.0/Log/Any.pm
    -r--r--r--  1 grr  staff  13991 Mar 28 16:02:15 2017 ./site_perl/5.26.0/Log/Any.pm
    $ ls -l ./site_perl/5.26.1/Log/Any.pm
    -r--r--r--  1 grr  staff  15354 Sep 28 16:59:27 2017 ./site_perl/5.26.1/Log/Any.pm

I deleted the version installed in site_perl/5.26.1 using `pm-uninstall` and then when a new version of `Log::Any` was available,  `cpm` correctly upgraded the version in site_perl/5.26.0 instead of re-installing a new version in site_perl/5.26.1.

**Comment by skaji** [comment]
What is your `perl -V`?

**Comment by skaji** [comment]
Okay, try `cpm install --global Log::Any`.

**Comment by skaji** [comment]
See https://github.com/skaji/cpm/issues/24

**Comment by grr** [comment]
`cpm install --global Log::Any` exhibited the same behavior. It installed the same version of the module in site_perl/5.26.1 as was already installed in site_perl/5.26.0.

**Comment by skaji** [comment]
What are
* `perl -V` for 5.26.0
* `perl -V` for 5.26.1

?

**Comment by grr** [comment]
As noted in the OP, I upgraded 5.26.0 to 5.26.1 using perlbrew. The upgrade happens in-place since  it's binary compatible.

    $ perl -V
    Summary of my perl5 (revision 5 version 26 subversion 1) configuration:
    
    Platform:
        osname=darwin
        osvers=16.7.0
        archname=darwin-thread-multi-2level
        uname='darwin grr.local 16.7.0 darwin kernel version 16.7.0: thu jun 15 17:36:27 pdt 2017; root:xnu-3789.70.16~2release_x86_64 x86_64 '
        config_args='-de -Dprefix=/Users/grr/src/perlbrew/perls/perl-5.26 -Dusethreads -Aeval:scriptdir=/Users/grr/src/perlbrew/perls/perl-5.26/bin'
        hint=recommended
        useposix=true
        d_sigaction=define
        useithreads=define
        usemultiplicity=define
        use64bitint=define
        use64bitall=define
        uselongdouble=undef
        usemymalloc=n
        default_inc_excludes_dot=define
        bincompat5005=undef
    Compiler:
        cc='cc'
        ccflags ='-fno-common -DPERL_DARWIN -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -I/opt/local/include'
        optimize='-O3'
        cppflags='-fno-common -DPERL_DARWIN -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -I/opt/local/include'
        ccversion=''
        gccversion='4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)'
        gccosandvers=''
        intsize=4
        longsize=8
        ptrsize=8
        doublesize=8
        byteorder=12345678
        doublekind=3
        d_longlong=define
        longlongsize=8
        d_longdbl=define
        longdblsize=16
        longdblkind=3
        ivtype='long'
        ivsize=8
        nvtype='double'
        nvsize=8
        Off_t='off_t'
        lseeksize=8
        alignbytes=8
        prototype=define
    Linker and Libraries:
        ld='env MACOSX_DEPLOYMENT_TARGET=10.3 cc'
        ldflags =' -fstack-protector-strong -L/usr/local/lib -L/opt/local/lib'
        libpth=/usr/local/lib /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/lib /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib /usr/lib /opt/local/lib
        libs=-lpthread -lgdbm -ldbm -ldl -lm -lutil -lc
        perllibs=-lpthread -ldl -lm -lutil -lc
        libc=
        so=dylib
        useshrplib=false
        libperl=libperl.a
        gnulibc_version=''
    Dynamic Linking:
        dlsrc=dl_dlopen.xs
        dlext=bundle
        d_dlsymun=undef
        ccdlflags=' '
        cccdlflags=' '
        lddlflags=' -bundle -undefined dynamic_lookup -L/usr/local/lib -L/opt/local/lib -fstack-protector-strong'


    Characteristics of this binary (from libperl): 
    Compile-time options:
        HAS_TIMES
        MULTIPLICITY
        PERLIO_LAYERS
        PERL_COPY_ON_WRITE
        PERL_DONT_CREATE_GVSV
        PERL_IMPLICIT_CONTEXT
        PERL_MALLOC_WRAP
        PERL_OP_PARENT
        PERL_PRESERVE_IVUV
        USE_64_BIT_ALL
        USE_64_BIT_INT
        USE_ITHREADS
        USE_LARGE_FILES
        USE_LOCALE
        USE_LOCALE_COLLATE
        USE_LOCALE_CTYPE
        USE_LOCALE_NUMERIC
        USE_LOCALE_TIME
        USE_PERLIO
        USE_PERL_ATOF
        USE_REENTRANT_API
    Built under darwin
    Compiled at Sep 22 2017 19:06:45
    %ENV:
        PERLBREW_BASHRC_VERSION="0.78"
        PERLBREW_HOME="/Users/grr/.perlbrew"
        PERLBREW_MANPATH="/Users/grr/src/perlbrew/perls/perl-5.26/man"
        PERLBREW_PATH="/Users/grr/src/perlbrew/bin:/Users/grr/src/perlbrew/perls/perl-5.26/bin"
        PERLBREW_PERL="perl-5.26"
        PERLBREW_ROOT="/Users/grr/src/perlbrew"
        PERLBREW_VERSION="0.78"
    @INC:
        /Users/grr/src/perlbrew/perls/perl-5.26/lib/site_perl/5.26.1/darwin-thread-multi-2level
        /Users/grr/src/perlbrew/perls/perl-5.26/lib/site_perl/5.26.1
        /Users/grr/src/perlbrew/perls/perl-5.26/lib/5.26.1/darwin-thread-multi-2level
        /Users/grr/src/perlbrew/perls/perl-5.26/lib/5.26.1
        /Users/grr/src/perlbrew/perls/perl-5.26/lib/site_perl/5.26.0
        /Users/grr/src/perlbrew/perls/perl-5.26/lib/site_perl

**Comment by skaji** [comment]
First:
I would say the code in your top comment does not imply that cpm has a problem,
because `$ cpm install Log::Any` tries to install Log::Any into `./local` (not global site inc).

Second:
I could not reproduce your issue in a docker container.
```
root@a28e743cd9d1:~# perl -V
Summary of my perl5 (revision 5 version 26 subversion 1) configuration:

  Platform:
    osname=linux
    osvers=4.4.0-53-generic
    archname=x86_64-linux-thread-multi
    uname='linux a28e743cd9d1 4.4.0-53-generic #74-ubuntu smp fri dec 2 15:59:10 utc 2016 x86_64 x86_64 x86_64 gnulinux '
    config_args='-de -Dprefix=/root/perl5/perlbrew/perls/perl-5.26.0 -Dusethreads -Duse64bitint -Aeval:scriptdir=/root/perl5/perlbrew/perls/perl-5.26.0/bin'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='cc'
    ccflags ='-D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    optimize='-O2'
    cppflags='-D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='5.4.0 20160609'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/gcc/x86_64-linux-gnu/5/include-fixed /usr/include/x86_64-linux-gnu /usr/lib /lib/x86_64-linux-gnu /lib/../lib /usr/lib/x86_64-linux-gnu /usr/lib/../lib /lib
    libs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=libc-2.23.so
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.23'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl):
  Compile-time options:
    HAS_TIMES
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_IMPLICIT_CONTEXT
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
    USE_REENTRANT_API
  Locally applied patches:
    Devel::PatchPerl 1.48
  Built under linux
  Compiled at Oct  3 2017 23:02:39
  %ENV:
    PERLBREW_BASHRC_VERSION="0.80"
    PERLBREW_HOME="/root/.perlbrew"
    PERLBREW_MANPATH="/root/perl5/perlbrew/perls/perl-5.26.0/man"
    PERLBREW_PATH="/root/perl5/perlbrew/bin:/root/perl5/perlbrew/perls/perl-5.26.0/bin"
    PERLBREW_PERL="perl-5.26.0"
    PERLBREW_ROOT="/root/perl5/perlbrew"
    PERLBREW_VERSION="0.80"
  @INC:
    /root/perl5/perlbrew/perls/perl-5.26.0/lib/site_perl/5.26.1/x86_64-linux-thread-multi
    /root/perl5/perlbrew/perls/perl-5.26.0/lib/site_perl/5.26.1
    /root/perl5/perlbrew/perls/perl-5.26.0/lib/5.26.1/x86_64-linux-thread-multi
    /root/perl5/perlbrew/perls/perl-5.26.0/lib/5.26.1
    /root/perl5/perlbrew/perls/perl-5.26.0/lib/site_perl/5.26.0/x86_64-linux-thread-multi
    /root/perl5/perlbrew/perls/perl-5.26.0/lib/site_perl/5.26.0
    /root/perl5/perlbrew/perls/perl-5.26.0/lib/site_perl

root@a28e743cd9d1:~# find /root/perl5/perlbrew/perls/perl-5.26.0/lib/site_perl
/root/perl5/perlbrew/perls/perl-5.26.0/lib/site_perl
/root/perl5/perlbrew/perls/perl-5.26.0/lib/site_perl/5.26.0
/root/perl5/perlbrew/perls/perl-5.26.0/lib/site_perl/5.26.0/x86_64-linux-thread-multi
/root/perl5/perlbrew/perls/perl-5.26.0/lib/site_perl/5.26.0/Log
/root/perl5/perlbrew/perls/perl-5.26.0/lib/site_perl/5.26.0/Log/Any.pm
/root/perl5/perlbrew/perls/perl-5.26.0/lib/site_perl/5.26.1
/root/perl5/perlbrew/perls/perl-5.26.0/lib/site_perl/5.26.1/x86_64-linux-thread-multi

root@a28e743cd9d1:~# perl cpanm -n Log::Any
Log::Any is up to date. (1.701)

root@a28e743cd9d1:~# perl cpm install -g Log::Any
DONE install Log::Any is up to date. (1.701)
0 distribution installed.
```

If you still think you have a problem, you may show me Dockerfile that reproduces the issue.

**Comment by skaji** [comment]
```Dockerfile
FROM ubuntu:16.04

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update
RUN apt-get install build-essential tar curl gzip -y

RUN curl -sSL -o /tmp/cpanm https://cpanmin.us
RUN curl -sSL -o /tmp/cpm   https://git.io/cpm

RUN curl -sSL https://install.perlbrew.pl | bash
RUN echo 'source ~/perl5/perlbrew/etc/bashrc' > ~/.bash_profile

SHELL ["bash", "-l", "-c"]

RUN perlbrew install --notest -j 4 5.26.0
RUN perlbrew switch perl-5.26.0
RUN perl /tmp/cpanm -nq Log::Any@1.700
RUN perlbrew upgrade-perl --notest -j 4
RUN perl /tmp/cpm install -g Log::Any@1.700
```
```
❯ docker build .
Sending build context to Docker daemon   2.56kB
Step 1/14 : FROM ubuntu:16.04
 ---> 2d696327ab2e
Step 2/14 : ENV DEBIAN_FRONTEND noninteractive
 ---> Using cache
 ---> b958510db1b8
Step 3/14 : RUN apt-get update
 ---> Using cache
 ---> ad97274b2d3a
Step 4/14 : RUN apt-get install build-essential tar curl gzip -y
 ---> Using cache
 ---> 82cc221afcd0
Step 5/14 : RUN curl -sSL -o /tmp/cpanm https://cpanmin.us
 ---> Using cache
 ---> 4da4a09b6a69
Step 6/14 : RUN curl -sSL -o /tmp/cpm   https://git.io/cpm
 ---> Using cache
 ---> c20b621af73a
Step 7/14 : RUN curl -sSL https://install.perlbrew.pl | bash
 ---> Using cache
 ---> d0aa177dff36
Step 8/14 : RUN echo 'source ~/perl5/perlbrew/etc/bashrc' > ~/.bash_profile
 ---> Using cache
 ---> 7b94d6220e85
Step 9/14 : SHELL bash -l -c
 ---> Using cache
 ---> 2de849f247e8
Step 10/14 : RUN perlbrew install --notest -j 4 5.26.0
 ---> Running in ff16d76a8b24
Fetching perl 5.26.0 as /root/perl5/perlbrew/dists/perl-5.26.0.tar.bz2
Download http://www.cpan.org/authors/id/X/XS/XSAWYERX/perl-5.26.0.tar.bz2 to /root/perl5/perlbrew/dists/perl-5.26.0.tar.bz2
Installing /root/perl5/perlbrew/build/perl-5.26.0 into ~/perl5/perlbrew/perls/perl-5.26.0

This could take a while. You can run the following command on another shell to track the status:

  tail -f ~/perl5/perlbrew/build.perl-5.26.0.log

perl-5.26.0 is successfully installed.
 ---> 0748d114f035
Removing intermediate container ff16d76a8b24
Step 11/14 : RUN perlbrew switch perl-5.26.0
 ---> Running in 39be22e00084
 ---> b2148a88e271
Removing intermediate container 39be22e00084
Step 12/14 : RUN perl /tmp/cpanm -nq Log::Any@1.700
 ---> Running in 66d59d23f04a
Successfully installed Log-Any-1.700
1 distribution installed
 ---> 6152cb23d498
Removing intermediate container 66d59d23f04a
Step 13/14 : RUN perlbrew upgrade-perl --notest -j 4
 ---> Running in 7a83a047f5cb
Upgrading perl-5.26.0 to 5.26.1
Fetching perl 5.26.1 as /root/perl5/perlbrew/dists/perl-5.26.1.tar.bz2
Download http://www.cpan.org/src/5.0/perl-5.26.1.tar.bz2 to /root/perl5/perlbrew/dists/perl-5.26.1.tar.bz2
Installing /root/perl5/perlbrew/build/perl-5.26.1 into ~/perl5/perlbrew/perls/perl-5.26.0

This could take a while. You can run the following command on another shell to track the status:

  tail -f ~/perl5/perlbrew/build.perl-5.26.1.log

perl-5.26.0 is successfully installed.
 ---> 5791ea496a13
Removing intermediate container 7a83a047f5cb
Step 14/14 : RUN perl /tmp/cpm install -g Log::Any@1.700
 ---> Running in 54d589147d24
DONE install Log::Any is up to date. (1.700)
0 distribution installed.
 ---> 69b524694b14
Removing intermediate container 54d589147d24
Successfully built 69b524694b14
```
cpm does not re-install Log::Any.
`DONE install Log::Any is up to date. (1.700)`
