### ISSUE TITLE
Doesn't work to install module from the private repository

### ISSUE THREAD

**Issue by ivanych** [skaji/cpm#113]
Hi, Shoichi,

It doesn't work to install module from the private repository.

```
$ cpm install https://gitlab.com/ivanych/cpm.git
Username for 'https://gitlab.com': ivanych
...
```
After entering login the password request must appear but instead nothing happens.

**Comment by skaji** [comment]
Please use http://user:password@example.com/ url, or ssh:// url (and setup ssh-agent if any).

**Comment by ivanych** [comment]
It's work! Thank you!
