### ISSUE TITLE
cpm [options] install 

### ISSUE THREAD

**Issue by ichesnokov** [skaji/cpm#13]
Hi, the 'cpm [options] install Module' syntax is actually not working: you should say 'cpm install Module [options]' instead - can you please either make it work as documented or fix the documentation?
App::cpm 0.111

**Comment by ichesnokov** [comment]
P.S. Can't we get rid of an "install" command entirely? I.e. to make it work more similar to cpanm so that 'cpm Module' would install Module.

**Comment by shoichikaji** [comment]
Which documentation? (Both `cpm --help` and `perldoc App::cpm` do not document options clearly :)) 
Try `cpm install [options] Module`.

**Comment by ichesnokov** [comment]
Good question :) Maybe I confused it with cpanm :-/ Well, maybe it's worth to make it more cpanm-compatible in this way?

**Comment by oalders** [comment]
This has confused me as well.  I was expecting it to "just work" like `cpanm`.  I think it would be fine to assume `install` if it's not provided.

**Comment by skaji** [comment]
cpm is not cpanm.
