### ISSUE TITLE
Fatpacked version that includes Carton::Snapshot

### ISSUE THREAD

**Issue by barefootcoder** [skaji/cpm#138]
I would like to get, or figure out how to create myself, a self-contained version of `cpm` which includes `Carton::Snapshot`.  This would help immensely in bootstrapping: I can check in my `cpanfile` and my `cpanfile.snapshot`, _and_ the fatpacked `cpm`, then merely checking out my repo gives me everything I need: I can install `local::lib`, whatever other modules I need, I get the exact versions of everything I expect, and so forth.  Without `Carton::Snapshot` in the fatpacked `cpm`, though, I either have to figure out a way to get `Carton::Snapshot` installed without using `cpm`, or I have to set aside my `cpanfile.snapshot` and accept that I might not get the exact versions I wanted.  Neither of those options seems palatable.

Do you see a good solution for this issue?

**Comment by skaji** [comment]
* Add Carton https://github.com/skaji/cpm/blob/master/author/fatpack.pl#L90
* Change 5.10.1 https://github.com/skaji/cpm/blob/master/author/fatpack.pl#L96
* Run `perl author/fatpack.pl --force`

**Comment by barefootcoder** [comment]
That sounds excellent, @skaji, and very close to what I was pondering doing anyway.  Thank you for the rapid response!  (And, can I just add: thank you for `cpm` in general.  It has become the linchpin of my current bootstrapping project, and is going to make our regular updates of local Perl modules **so** much faster.)

One last question: Do I have to worry about that version number conflicting with some real, future version of `cpm`?

**Comment by barefootcoder** [comment]
Oh ... heheh.  I misread that.  That version number is not a `cpm` version, but rather a Perl version.  I suppose that's the minimum you need to run `Carton` ... interesting.  I don't think that will impact us, but it's certainly good to keep in mind.

**Comment by barefootcoder** [comment]
Okay, I'm pretty sure it works with Perl 5.8.5, which seems to be the minimum that Carton will put up with.  Hopefully I can figure out soon why `perlbrew` won't build me a 5.8.5 to test that out so I can verify that's the case.  I scripted the necessary tweaks and have included the heart of that (bash) script below for posterity/lurkers.  Some of it could theoretically be made easier by some tweaks to the fatpacker script (e.g. changing a `use` to a `require` to avoid a never-used dependency, adding another switch, etc), but I realize I'm already using `fatpack.pl` in a way it was never designed to be used, so I won't push my luck too much. :-D

Thx again @skaji.  I think we can call this issue closed.

The main part of my `cpm-upgrade` script (`bash` syntax):
```
    OUR_DESCR="'built by $ME from ${current_head:0:10}','$github_url/tree/$branch'"
    tweak_source='      
        $_ = "use 5.8.5;" if /use\s+5\./;                               # can get by with minimal Perl
        $_ = "\n" if /FindBin/;                                         # neither need nor want anything from this
        $_ = "\n" if /use\s+CPAN::Meta::Requirements/;                  # next line circumvents this dependency
        $_ = "" if /gen_snapshot/ and not /sub\s+gen_snapshot/;         # no need to generate a snapshot
        s/^\s+// if s/<<~"(.+)"/$E=$1,qq|<<"$E"|/e../^\s*$E$/;          # fixup for 5.26-specific heredoc syntax
        s/5\.\d+\.\d+/5.8.5/ if /target\s*=/;                           # Carton requires at least this much Perl
        s|=\s*git_info\b|= ('"$OUR_DESCR"')|;                           # substituting our own info here
        s/$/ Carton/ if /extra\s*=\s*qw/;                               # the main reason for the song and dance
    '
    perl -pe "$tweak_source" fatpack.pl | perl -I../lib - --force
    mv -f ../cpm $CPM
```
What I had to add to my `cpanfile` to be able to run it:
```
        requires 'App::cpm';
        requires 'App::FatPacker::Simple';
        requires 'Carton::Snapshot';
```

**Comment by skaji** [comment]
For the record,
the reason why I bump perl requirement to 5.10.1 is that Path::Tiny requires an XS module Digest::SHA, which is not core in perl 5.8.

I'm happy cpm helps you!

**Comment by barefootcoder** [comment]
> For the record, the reason why I bump perl requirement to 5.10.1 is that Path::Tiny requires an XS module Digest::SHA, which is not core in perl 5.8.

I see.  Well, I'm still hoping to actually _try_ it with 5.8.5 and see how it goes, but I've gotten distracted by other stuff.

> I'm happy cpm helps you!

It really is the centerpiece of our DarkPAN solution at this point.  I don't think there's anything else that lets me put _only_ the modules that we've actually patched into our DarkPAN dir, then just say "get these other exact versions from CPAN."  I couldn't figure out how to make Carton do what I wanted, but `cpm` (with a little wrapping for convenience) really hits the spot.  I wish more people knew about it.  (At some point perhaps I'll do a blog post about it ...)

**Comment by skaji** [comment]
> At some point perhaps I'll do a blog post about it ...

Sounds great:)
