### ISSUE TITLE
Possibility to run tests

### ISSUE THREAD

**Issue by ichesnokov** [skaji/cpm#14]
cpm doesn't run tests by default, and it seems like it's not possible to say it to do so. I think it can be useful to provide an option for it to run tests - and make it possible to specify this option in a configuration file / environment variable to make it a default.

**Comment by shoichikaji** [comment]
Will do, thanks!

**Comment by shoichikaji** [comment]
@ichesnokov Released https://metacpan.org/release/SKAJI/App-cpm-0.112

>  make it possible to specify this option in a configuration file / environment variable

Let me think about it.

**Comment by skaji** [comment]
use `--test` option.
