### ISSUE TITLE
Multiple --mirror options now silently fail

### ISSUE THREAD

**Issue by willsheppard** [skaji/cpm#150]
The following command used to work (guessing before v0.981?), now it fails:
```
cpm install -v --mirror $PINTO_MIRROR --mirror http://cpan.metacpan.org --mirror-only
76103 FAIL resolve   (0.004sec) Foo::Bar
FAIL resolve Foo::Bar
0 distribution installed.
See /Users/user/.perl-cpm/build.log for details.
```

It appears to be due to this change:
https://github.com/skaji/cpm/commit/b5a318a972bb3f600ebe05a5c7aa4f45ace09cd8#diff-a5723d16cbf7723e26f0310aa2438195R73

It would be better if the app adhered to the "principle of least astonishment". At the very least a warning should be printed "multiple --mirror options not supported, ignoring... whatever".
Even better would be to error and abort if multiple mirror options are used.

Also [the POD still says](https://metacpan.org/pod/distribution/App-cpm/script/cpm) you *can* use --mirror multiple times! That is quite disappointing.

**Comment by skaji** [comment]
@willsheppard Thanks for reporting this. I'll fix doc.

By the way, do you have use-cases that uses multiple `--mirror` options?

**Comment by willsheppard** [comment]
Yes, we do this when building all of our internal repos, to pull in dependencies from both CPAN and our DarkPAN

**Comment by willsheppard** [comment]
Hoping the new doc explains the recommended way to use multiple mirrors

**Comment by skaji** [comment]
I see.

Does you darkpan have 02packages.details.txt.gz? If yes, try this:
```
cpm install --resolver 02package,http://your-dakpan.com --resolver metadb Module1 Module2 ...
```

**Comment by willsheppard** [comment]
Yes, that does work for us, thank you.

Will `--resolver` be marked as not experimental anymore, too?

**Comment by willsheppard** [comment]
And a `warn` in the code if someone tries to use multiple `--mirror` would still be nice and helpful for other people.

**Comment by skaji** [comment]
Currently I'm working on cpm 1.0.

I'm not 100% sure yet,
but in 1.0, I will deprecate `--mirror` and `--resolver` options, and introduce a new option `--source`.

**Comment by willsheppard** [comment]
Sounds great 👍

**Comment by willsheppard** [comment]
Please consider this update to the documentation in the meantime. It's been over a month with the docs containing incorrect information.
