### ISSUE TITLE
Question: Installing local dependencies

### ISSUE THREAD

**Issue by Shawak** [skaji/cpm#153]
Hello,

I recently ran into problems with cpanm using my own pinto repo which I could fix replacing cpanm with cpm, but sadly there doesn't seem to be any equivalent to 'cpanm --installdeps .' (Installing local dependencies). Because using `cpm .` doesn't work (it's trying to install from my local directory). Do I need to generate a cpanfile or is there any workaround? I couldn't find anything in `-help`.

Cheers

**Comment by skaji** [comment]
Need cpanfile.
