### ISSUE TITLE
Devel::Peek should not raise an error when trying to update

### ISSUE THREAD

**Issue by atoomic** [skaji/cpm#161]
When trying to plug Continuous integration using GitHub workflows I noticed that the following command cannot be used

`dzil listdeps | cpm install -g --show-build-log-on-failure -`

because Devel::Peek is listed in the dependencies and as Devel::Peek is part of Perl itself, it fails to update... https://metacpan.org/pod/Devel::Peek

```
╰─> cpm install -g Devel::Peek
FAIL install Cannot upgrade core module Devel::Peek.
FAIL install Devel::Peek
0 distribution installed.
See /Users/nicolas/.perl-cpm/build.log for details.
```

The temporary solution is to use `cpanm` which does not raises an error when trying to install Devel::Peek
`╰─> cpanm Devel::Peek`

In a global way, if a module is not dual life and only provided by Perl, we should not got a failure when trying to install it.

**Comment by skaji** [comment]
Thanks for the report.

I actually think the current cpm behavior makes sense.
Let me think about it.

**Comment by ferki** [comment]
This one keeps biting my use cases for a long time too (mostly in CI context).

Would it be a viable option to mark these cases as `SKIP` instead of `FAIL`, and also letting the exit code indicate success?

**Comment by ferki** [comment]
Thanks, @skaji for fixing this! It works great for many of my use cases :+1:
