### ISSUE TITLE
empty list via pipe leads to error message and return code

### ISSUE THREAD

**Issue by abraxxa** [skaji/cpm#165]
If the list returned by e.g. `dzil authordeps --missing` is empty, cpm throws and error and returns a return code != 0:
```
$ dzil authordeps --missing | cpm install -
Need arguments or cpanfile.
```
This breaks our CI in case there is nothing to do.

**Comment by skaji** [comment]
@abraxxa Thanks for reporting this. Fixed in https://metacpan.org/release/SKAJI/App-cpm-0.993
