### ISSUE TITLE
POD does not discuss installing into a Perl installed with PerlBrew

### ISSUE THREAD

**Issue by ronsavage** [skaji/cpm#169]
It would be good to be able to do as per the subject. Perhaps it's the default? Who knows! The docs are silent on this issue.

**Comment by skaji** [comment]
I'm not quite sure what you mean.

cpm installs modules into `.local` by default.
If you want cpm to install modules into the global `@INC`, then set `--global` flag.
Please check App::cpm::Tutorial.

**Comment by ronsavage** [comment]
Thanx for the quick reply. You can close this ticket now.
