### ISSUE TITLE
Tests fail and test timeout is not respected for Term::ReadKey

### ISSUE THREAD

**Issue by tadzik** [skaji/cpm#176]
Term::Readkey, when testing its [SetControlChars](https://metacpan.org/source/JSTOWE/TermReadKey-2.38/t/02_terminal_functions.t#L91) function hangs while calling [tcsetattr](https://github.com/jonathanstowe/TermReadKey/blob/master/genchars.pl#L239) when ran under cpm. In addition to that, cpm's `--test-timeout` setting doesn't seem to be respected in this case. Reproducible with `cpm install --test-timeout=3 --test Term::ReadKey` which hangs forever. Installing the same module with cpanm works fine.

The problem seems to be running the testing job in the background thread: [tcsetattr is apparently not allowed to do anything unless it's in the foreground](https://superuser.com/questions/1201284/why-cant-we-call-tcsetattr-function-to-set-pseudo-terminals-setting-when-the-c). I'm not sure if the problem is solvable on the cpm side (unless it attempts to retry the tests on the main, foreground thread if it fails in the background), but I'd expect it to at least fail after the specified timeout.

**Comment by skaji** [comment]
Thanks. I will look into it.

**Comment by skaji** [comment]
Fixed https://github.com/jonathanstowe/TermReadKey/pull/35
