### ISSUE TITLE
Usage with OPAN broken by 0.997003

### ISSUE THREAD

**Issue by abraxxa** [skaji/cpm#196]
The use of CPAN::02Packages::Search breaks usage with OPAN:

```
cpm install -g --show-build-log-on-failure --resolver 02packages,$CPAN_MIRROR --mirror $CPAN_MIRROR
/bin/gzip -dc /root/.perl-cpm/sources/http%darkpan.example.org%combined/02packages.details.txt.gz: 
gzip: /root/.perl-cpm/sources/http%darkpan.example.org%combined/02packages.details.txt.gz: not in gzip format
error building image: error building stage: failed to execute command: waiting for process to exit: exit status 25
```

Where $CPAN_MIRROR is http://darkpan.example.org/combined/

**Comment by abraxxa** [comment]
The file exists but isn't gzipped.

**Comment by skaji** [comment]
Does your darkpan have gzipped 02packages details txt?

**Comment by skaji** [comment]
I see.

**Comment by abraxxa** [comment]
darkpan.example.org/custom/modules/02packages.details.txt.gz seems to serve an un-gzipped file although index.gz on disk is compressed. This did work until the latest cpm version.
I'm investigating the issue with mst and keep you updated.

**Comment by abraxxa** [comment]
I was able to fix the issue in App::Opan by changing the order of https://github.com/shadowcat-mst/App-opan/blob/v0.003002/script/opan#L315-L317 and https://github.com/shadowcat-mst/App-opan/blob/v0.003002/script/opan#L318-L320 so the longer url comes first.
