### ISSUE TITLE
Cannot require self-contained cpm without running it

### ISSUE THREAD

**Issue by XSven** [skaji/cpm#211]
Recently I have used a self-contained _cpanm_ file in the following way

```perl
require 'cpanm';
my $cpanm = App::cpanminus::script->new;
...
```

Now I wanted to replace _cpanm_ with a self-contained _cpm_ file using the same approach

```perl
require 'cpm';
my $cpm = App::cpm::CLI->new;
...
```
The `require` fails with the message

>Need subcommand, try `cpm --help`

Seemingly the self-contained _cpm_ is not implemented as a modulino ([Scripts as Modules](http://www.drdobbs.com/scripts-as-modules/184416165)).

- Can this be changed short-term?!
- Is there another way how I can load a self-contained _cpm_ and control its execution separately?

**Comment by skaji** [comment]
After installing App::cpm module from CPAN, you could use App::cpm::CLI.

But please note that the use of App::cpm::CLI is not supported and I will change the internal of cpm whenever I want.

**Comment by skaji** [comment]
There is no way to use self contained cpm as a module.

**Comment by XSven** [comment]
This is a pity. I want to use cpm in another perl project. I dislike to start a perl program from another perl program using a `system()` call.
