### ISSUE TITLE
Log file is messy

### ISSUE THREAD

**Issue by estrabd** [skaji/cpm#22]
All workers currently emit to a single file, resulting in a mixed and messy log file. (added after YAPC talk =)

**Comment by skaji** [comment]
@estrabd thank you for your opening this issue!

**Comment by estrabd** [comment]
(sorry for the PM here) You're welcome. I added your module to the PRC list for tonight at YAPC - maybe someone will choose it. Feel free to join us! http://tinyurl.com/prc-module-list

**Comment by skaji** [comment]
done in #59
