### ISSUE TITLE
Doesn't handle local::lib

### ISSUE THREAD

**Issue by pwr22** [skaji/cpm#24]
This is similar to https://github.com/skaji/cpm/issues/12

It would be nice if `cpm` would honour the same logic for installing modules to `local::lib` set locations as `cpanm` has

**Comment by skaji** [comment]
Please use `-g` option.

**Comment by pwr22** [comment]
Ah, this will respect the normal environment that `local::lib` sets?

**Comment by pwr22** [comment]
It does in fact appear to thanks. Might be worth making the docs a little clearer though since logically this isn't a "global" installation to me

**Comment by pwr22** [comment]
@skaji Ah, looks like you've already added to the docs. Thanks 👍

**Comment by skaji** [comment]
@pwr22 You're welcome 😄
