### ISSUE TITLE
Does not support all of cpanm's options

### ISSUE THREAD

**Issue by oalders** [skaji/cpm#26]
@skaji, first of all, thanks very much for your efforts.  :)  I'm looking into implement this at `$work`, but I need to be able to pass the following flags:

`--mirror-only`
`--mirror-index`
`--with-develop`
`--sudo`

If you're open to adding support for these, I'd be happy to send a pull request.

**Comment by skaji** [comment]
I'm happy to hear you tried cpm!
I have a plan to implement those into cpm.

As for `--mirror-only` and `--mirror-index`, what is your actual use case for those?

Everytime I use the following options and some combination with these,
I'm confused and I have to look at cpanm source code.
```
--mirror
--mirror-only
--mirror-index
--cascade-search
--from
```

**Comment by oalders** [comment]
We keep all of our modules in our own CPAN mirror.  It's basically a minicpan of mostly CPAN modules and some of our own private forks.  So, we never want `cpanm` to install a module from a mirror other than our own, which is why we use `--mirror-only` and `--mirror-index`.

It _might_ be helpful to pass all flags that `cpm` does not recognize directly on to `cpanm`.

**Comment by zdm** [comment]
I want to migrate from cpanm to cpm, but support for cpanm --with-xxx options is required.

**Comment by oalders** [comment]
I tried to hack something together here https://github.com/oalders/cpm/tree/more-cpan-options but I ran out of $work time.

**Comment by perlancar** [comment]
Yeah, `--mirror-only` is basically my number one wishlist too (after that, multiple `--mirror`). So I can work completely offline.

`--mirror-only` is when you resolve not by using cpanmetadb (which requires network access), but by parsing `modules/02packages.details.txt.gz` from the mirror.

**Comment by skaji** [comment]
@oalders @perlancar 
Could you try `wip` branch?
```
wget https://raw.githubusercontent.com/skaji/cpm/wip/cpm
perl cpm -h
perl cpm install --mirror file://path/to/darkpan --mirror-only Your::Module
perl cpm install --mirror http://example.com/darkpan --mirror-only Your::Module
```

**Comment by oalders** [comment]
@skaji thanks for this.  I've put in a request at $work to schedule time for someone to test this out.

**Comment by perlancar** [comment]
@skaji Cool, it works!

**Comment by skaji** [comment]
OK, I have implemented `--mirror-only` in `wip` branch.
Here `--mirror DARKPAN --mirror-only` means:
* resolve distributions from DARKPAN/modules/02packages.details.txt.gz
* fetch distributions from DARKPAN/authors/id/


BTY, I think a lot of people want a resolver/fetcher that:
* resolve/fetch distributions against their darkpan first
* and if that fails, resolve distributions against metadb and fetch them from normal CPAN mirror

i.e.
```
my $r1 = App::cpm::Resolver::Mirror->new(mirror => "http://example.com/darkpan/");
my $r2 = App::cpm::Resolver::MetaDB->new(mirror => ["http://www.cpan.org/"], uri => "http://cpanmetadb.plackperl.org/v1.0/");
my $c = App::cpm::Resolver::Cascade->new;
$c->add($r1);
$c->add($r2);
return $c;
```

I want to add an option to cpm for the above resolver/fetcher.
What option name is appropriate?

P.S. Actually I'm not a big fan of `--mirror-only` option name, because from that name,
I cannot imagine it means to use `DARKPAN/modules/02packages.details.txt.gz` to resolve distribution names.

**Comment by perlancar** [comment]
How about --resolve-order? The default is:

    --resolve-order metadb

and user can change it to one of:

    --resolve-order 02packages  ;# the same as --mirror-only
    --resolve-order 02packages,metadb
    --resolve-order metadb,02packages

**Comment by skaji** [comment]
@perlancar  Thank you.

I think it is nice to be able to specify both

* where to resolve distribution names/locations
* where to fetch distbutions

at the same time.

So how about this:
```
cpm install \
  --resolver 02packages,http://example.com/darkpan \
  --resolver metadb,http://www.cpan.org,http://backpan.perl.org \
  --resolver metacpan \
  Some::Module
```
which means 1st 02package -> 2nd metadb -> 3rd metacpan.

This is a little bit annoying though:/

**Comment by skaji** [comment]
```
I think it is nice to be able to specify both
* where to resolve distribution names/locations
* where to fetch distbutions
at the same time.
```

... This is not correct because some "resolver" has no distinction between "where to resolve" and "where to fetch".


So I mean:
```
cpm install \
  --resolver resolver_class1,arg1,arg2,... \
  --resolver resolver_class2,arg1,arg2,... \
  --resolver resolver_class3,arg1,arg2,... \
  Some::Module
```

**Comment by perlancar** [comment]
I'm okay with the option syntax. For convenience, 02packages should default to the first (last?) mirror, so:

    % cpm install --mirror http://mirror1/ --resolver 02packages --resolver metacpan 

is equivalent to:

    % cpm install --mirror http://mirror1/ --resolver 02packages,http://mirror1/ --resolver metacpan

Also, you can support --mirror-only for cpanm compatibility which is equivalent to:

    --resolver 02packages

**Comment by perlancar** [comment]
Another thing you can consider is, if there is only one --mirror, and mirror URL is file:/ or a filesystem path, instead of the default:

    --resolver metadb

perhaps cpm can default to:

    --resolver 02packages

since the user probably wants offline mode.

**Comment by skaji** [comment]
@perlancar Thank you very much. I'll think it over.

**Comment by oalders** [comment]
@skaji thanks.  It works for us!

**Comment by skaji** [comment]
Because mirror related options has been implemented, I close this issue.
I opened with-develop #56 issue. If you think it is nice, please comment there.

**Comment by eserte** [comment]
What about `--sudo`?

**Comment by skaji** [comment]
You can use --sudo option.

**Comment by eserte** [comment]
Indeed, "sudo" appears in the code. However, the documentation does not mention a `--sudo` option.
