### ISSUE TITLE
Sould suport vx.x.x version format in cpanfile

### ISSUE THREAD

**Issue by zdm** [skaji/cpm#30]
Hi.

Currently, if version is specified in version string, cpm throw error.

eg:
```
requires 'Geo::IP', v1.45.0;
requires 'GeoIP2',  v2.3.1;
```

**Comment by skaji** [comment]
Thank you for your reporting.
Fixed in current master.

**Comment by skaji** [comment]
Ugh, perl5.8...

**Comment by zdm** [comment]
Yeah, perl 5.8 makes our life harder.

**Comment by skaji** [comment]
The problem seems to be
older Storable does not properly save/restore "magic_vstring".
https://github.com/Perl-Toolchain-Gang/CPAN-Meta-Requirements/blob/master/lib/CPAN/Meta/Requirements.pm#L87-L104

**Comment by zdm** [comment]
Are you sure, that support for such old perl is required?
Maybe better to forget about this?
