### ISSUE TITLE
Pls, add possibility to read modules list from STDIN

### ISSUE THREAD

**Issue by zdm** [skaji/cpm#31]
This is required for using cpm with cpan-outdated or similar tools.

Typical usage:

```
cpan-outdated | cpanm
```

**Comment by eserte** [comment]
As a workaround, one could probably use `cpm $(cpan-outdated)`. This should work unless the module list is very large, exceeding the maximum cmdline length. The other possible problem with backticks (whitespace and special shell metacharacters in arguments) should not happen with CPAN distribution files, I think.

**Comment by zdm** [comment]
Why not just read from STDIN until it will be closed?
This can be implemented in 3 lines of code.

**Comment by zdm** [comment]
Also, cpm currently not support packages in full, for example "T/TO/TODDR/Locale-Maketext-1.28.tar.gz", format.
