### ISSUE TITLE
backpan support

### ISSUE THREAD

**Issue by mark-5** [skaji/cpm#35]
cpanm defaults to trying to fetch dists from backpan.perl.org when searching both cpanmetadb and metacpan. This is needed whenever cpanfiles pin old versions of modules that have since been cleaned from cpan.

Just out of curiosity, is there a reason cpm implemented its own cpanmetadb resolver, instead of using one of the Menlo::Index::* modules?

**Comment by mark-5** [comment]
Looks like pinning versions doesn't work if the version is not latest. So this isn't just an issue with modules on backpan, cpm doesn't do history lookups and won't find any module that's not the latest version.

**Comment by skaji** [comment]
Current master uses the backpan.

> is there a reason cpm implemented its own cpanmetadb resolver, instead of using one of the Menlo::Index::* modules?

Menlo::Index::MetaDB does not use keep-alive http request.

I will change cpm so that it uses MetaCPAN v1 API or MetaDB history API or ....

**Comment by mark-5** [comment]
> Current master uses the backpan.
Sorry, haven't pulled from upstream in a few weeks. Nice!

> Menlo::Index::MetaDB does not use keep-alive http request.
That sounds like a pretty good reason :)

Nice job with this, btw. I'm really excited to see what eventually happens with carton/carmel integration.

**Comment by mark-5** [comment]
If the Menlo::Index classes used HTTP keep-alive, would it then make sense to use them in cpm? Or is there anything else I may be missing, that would make using them in cpm unnecessary or a bad idea?

It looks like it would be pretty simple to add keep-alive support to menlo(I've got a fork [here](https://github.com/mark-5/cpanminus/tree/http-keep-alive)), and I think these classes would really simplify using the metacpan/metadb history APIs.
