### ISSUE TITLE
wishlist: Support -v for --version too like in cpanm

### ISSUE THREAD

**Issue by perlancar** [skaji/cpm#40]
Although --version is -V and --verbose is -v, since -v is popular to request version, cpanm also supports this:

    % cpanm -v

to display version.

**Comment by skaji** [comment]
I guess `cpanm -v` means `cpanm --verbose`.

**Comment by perlancar** [comment]
Yes, but the effect is `cpanm -v` does show the version numbers instead of showing an error message like `cpm -v`:

    Missing subcommand, try `cpm --help`

**Comment by skaji** [comment]
* `cpm --help` clearly states: `-V, --version` shows version
* `cpanm -v` means verbosity. It is true that `cpanm -v` shows version of cpanm, but it's just a side effect.
