### ISSUE TITLE
cpm does not install DB_File

### ISSUE THREAD

**Issue by eserte** [skaji/cpm#42]
If `DB_File` is specified in a cpanfile, then it seems that `cpm` does not install this module.

A sample build log with this problem can be found here: https://api.travis-ci.org/jobs/171750983/log.txt?deansi=true

If `DB_File` is specified as a `cpm` command line argument, then installation works.

A quick look into the `cpm` code seems to suggest that core modules are marked as "satisfied". `DB_File` is a core module, but it is an optional one, so depending on perl's configuration it may be there or not (more specifically, if something like `libdb*-dev` is installed during perl's configuration, then `DB_File` will be built, otherwise not).

I guess that other optional core modules like `GDBM_File` have the same problem.

**Comment by skaji** [comment]
@eserte Thanks for your report. Will fix.

**Comment by skaji** [comment]
@eserte Please try https://metacpan.org/release/SKAJI/App-cpm-0.293

**Comment by eserte** [comment]
Confirmed --- I see a successful install of DB_File now, see https://travis-ci.org/eserte/bbbike/jobs/183011685#L496
