### ISSUE TITLE
02packages cache not getting updated 

### ISSUE THREAD

**Issue by oschwald** [skaji/cpm#47]
We have been running into an issue where the `02packages` cache in `.perl-cpm/sources` is not always getting updated correctly. Our darkpan lives in a Git repo with multiple branches. We pass it to `cpm` using `--resolver 02packages,file://...`. What I think is happening is that sometimes the cache has a newer `mtime` even though it is out of date. This can happen when the user uses an older checkout with `cpm` and then later tries to install using the newer version.

**Comment by skaji** [comment]
@oschwald thanks for your report.
Please try https://metacpan.org/release/SKAJI/App-cpm-0.213
