### ISSUE TITLE
Failure to run the app

### ISSUE THREAD

**Issue by ZzZombo** [skaji/cpm#48]
`C:\> cpm install --verbose Code::TidyAll`
`Use of uninitialized value $ENV{"HOME"} in concatenation (.) or string at I:/Dwimperl/perl/site/lib/App/cpm.pm line 25.`
`local: No such file or directory at I:/Dwimperl/perl/site/lib/App/cpm.pm line 64`

I use the latest Dwimperl distribution, on Windows 10 x64. Installed as written via cpanm with no issues.

**Comment by skaji** [comment]
Thanks for your report.

Actually I have not used cpm in windows environment. From your outputs, it seems that
* windows does not have HOME environment variable  
https://github.com/skaji/cpm/blob/master/lib/App/cpm.pm#L26
* the behaviour of abs_path in windows is different from that in Linux/macOS.  
https://github.com/skaji/cpm/blob/master/lib/App/cpm.pm#L64

If you are interested, could you try cpm with fixes for above issues?

**Comment by ZzZombo** [comment]
Sorry, I don't understand what am I supposed to try, there is no new version.

**Comment by skaji** [comment]
I guess you know things about windows better than me.
So if you are willing to help cpm work in windows, please fix above issues yourself and let me know what happens.

**Comment by ZzZombo** [comment]
Ah. I'll take a look, but it may take a while, since I don't really have any tools other than Perl to work with on this, setting them up will take time.

**Comment by eserte** [comment]
Regarding the `$ENV{HOME}` issue: I think the Windows replacement would be `"$ENV{HOMEDRIVE}$ENV{HOMEPATH}"`. Alternatively one could use `File::HomeDir->my_home`, but this would add another non-core dependency.

**Comment by skaji** [comment]
Closed by charsbar's commit 0968710
