### ISSUE TITLE
cpanfile recursive resolving

### ISSUE THREAD

**Issue by ivanych** [skaji/cpm#50]
Hi Shoichi,

I discovered **cpm** and very happy about it. Thank you a lot for this useful utility!

Unfortunatelly I found out that **cpm** can't resolve cpanfile recursively.

For instance, in cpanfile of module X there is dependence from module Y and in cpanfile of module Y there is dependence from module Z. In that case command **cpm X** will install module X, but won't install modules Y and Z.

If you download module X and run the command **cpm** in it then module Y will be installed, but module Z won't be installed anyway.

Are you planning to add the ability to recursively resolve cpanfile? That would be great!

**Comment by skaji** [comment]
Could you give me an example?

**Comment by ivanych** [comment]
cpm install git@github.com:ivanych/Test-Test.git

Dependencies from cpanfile won't be installed:(

**Comment by skaji** [comment]
In general, when installing distributions,
CPAN clients retrieve dependencies from META.json(MYMETA.json) not from cpanfile.

**Comment by ivanych** [comment]
Yes, I understand. But I'd like to take dependencies exactly from cpanfile. Because in cpanfile you can define git and in META you can't.

**Comment by skaji** [comment]
Okay, I understand your request now.
> Are you planning to add the ability to recursively resolve cpanfile? That would be great!

Unfortunately, no.

I guess Perl community has the consensus that the dependencies for CPAN distribuitons must be described in META files. And I agree with that.

**Comment by ivanych** [comment]
But how then define that dependency is in gif?

**Comment by skaji** [comment]
Not supported.

**Comment by ivanych** [comment]
I'm crying:(
