### ISSUE TITLE
More diagnostics in case of failures

### ISSUE THREAD

**Issue by eserte** [skaji/cpm#51]
For one of my github projects with a large dependency list I replaced cpanm with cpm for travis-ci testing. This gives me some speed improvements (formerly ~300s for dependency installation, now ~200s). But unfortunately there are occasional fails:
* https://travis-ci.org/eserte/bbbike/jobs/175221900 (1st attempt)
  perl 5.10.1 -> FAIL configure (0.115sec) File-Share-0.25
* https://travis-ci.org/eserte/bbbike/jobs/175221900 (2nd attempt)
  perl 5.10.1 -> FAIL configure (0.138sec) Array-Heap-3.21
* https://travis-ci.org/eserte/bbbike/jobs/175534860
  perl 5.8.8 -> FAIL configure (0.183sec) JSON-2.90
* https://travis-ci.org/eserte/bbbike/jobs/177167612
  perl 5.8.8 -> FAIL configure (0.165sec) JSON-2.90

So this happens only for older perls (the tested perl versions here range from 5.8 to 5.20). I see no pattern in the affected CPAN modules. And successful installations with these perls may also happen (for example this build: https://travis-ci.org/eserte/bbbike/builds/175858436 )

Unfortunately I don't know a way in finding out the reasons for the failures. It would be nice if there was more information in case of errors, e.g. output the log for the failing module at the end of the installation. Or maybe there's already a log file of the build process, but it's not documented.

**Comment by skaji** [comment]
@eserte thank you for your reporting. First, I will try to reproduce the failures.

**Comment by skaji** [comment]
FYI: This might help you find the reason of failures.
```
cat `ls -t ~/.perl-cpm/build.* | head -1`
```

**Comment by skaji** [comment]
@eserte It would be very helpful if you could give me a reduced testcase that demonstrates the failures in our local macOS or Linux (Ubuntu or Centos).

**Comment by eserte** [comment]
As I already wrote --- the failures are occasional, it does not happen on every travis-ci run. It could be a race condition, a timing problem, network hiccups... that's why it's good to have the diagnostics. It would be nice if there was even a cpm option to output the logs automatically on failures (e.g. `--show-logs-on-failure`).

The last builds of my project had no problems during the cpm installation phase, so we have to wait for diagnostics (but this would be another issue anyway).

**Comment by skaji** [comment]
@eserte 
I released https://metacpan.org/release/SKAJI/App-cpm-0.290, which contains #59 

Could you try it, and find out the reason of failures by
```
cpm install ... || cat ~/.perl-cpm/build.log
```
