### ISSUE TITLE
idea: support distroprefs

### ISSUE THREAD

**Issue by skaji** [skaji/cpm#52]
I'm thinking of adding *hook points* to cpm somehow.

Some use-cases might be:
* inject dependencies
* patch distributions
* ...?

charsbar pointed out [Distroprefs](https://metacpan.org/pod/CPAN::Distroprefs) to me.
Actually I haven't used distroprefs. Are distroprefs useful?

**Comment by glasswalk3r** [comment]
Yes, they are! Specially for [CPAN testers](http://cpantesters.org/), were we use them to disable modules that doesn't behave well when running their tests in an automated fashion.
But you can also use distroprefs to do a lot of things regarding how to customize a module should run in your environment.
