### ISSUE TITLE
Fails if ~/.perl-cpm does not exist (App-cpm-0.290)

### ISSUE THREAD

**Issue by eserte** [skaji/cpm#60]
cpm fails if `~/.perl-cpm` does not exist. Sample failed run can be seen on https://travis-ci.org/eserte/sandbox/jobs/182802980

These are the interesting lines from the log:
```
$ if ! cpm install -g -v; then cat ~/.perl-cpm/build.log; false; fi

/home/travis/.perl-cpm/build.log.1481356160: No such file or directory at /home/travis/perl5/perlbrew/perls/5.10/lib/site_perl/5.10.1/App/cpm/Logger/File.pm line 9.

cat: /home/travis/.perl-cpm/build.log: No such file or directory
```

My workaround: do a `mkdir ~/.perl-cpm` myself, as done in https://travis-ci.org/eserte/sandbox/jobs/182803524

**Comment by skaji** [comment]
@eserte sorry. please try https://metacpan.org/release/SKAJI/App-cpm-0.291

**Comment by eserte** [comment]
Thanks. I tried 0.292 and it looks good.
