### ISSUE TITLE
MSWin32 MSYS2: cpm logging causes configure process failure

### ISSUE THREAD

**Issue by zmughal** [skaji/cpm#77]
When running `cpm install` on MSYS2's MINGW64 subsystem, I get the following error:

```
The process cannot access the file because it is being used by another process.
```

I have tracked it down to the line: [App::cpm::Worker::Installer::Menlo/run_command](https://github.com/skaji/cpm/blob/0.301/lib/App/cpm/Worker/Installer/Menlo.pm#L65)

```perl
 $cmd .= " >> " . Menlo::Util::shell_quote($self->{log}) . " 2>&1";
```

Since the workers are trying to write to a file that is already open, the process gets killed by Windows.

**Comment by skaji** [comment]
@zmughal thanks for reporting this.

**Comment by skaji** [comment]
close this issue by #98
