### ISSUE TITLE
Support adjusting the Menlo configure_timeout

### ISSUE THREAD

**Issue by arodland** [skaji/cpm#81]
I'm using cpm on a very slow machine. I want to use cpm *because* the machine is very slow and cpm will speed up the install a little bit. But sometimes a large dist like Moose will take more than 60 seconds for the configure stage, causing the whole build to bail out with "Terminated". I would like to have the option to wait longer :)

**Comment by skaji** [comment]
The request itself seems to be reasonable.
On the other hand, I'm not sure cpm will speed up the installation on such a slow machine.

**Comment by arodland** [comment]
True enough, I'm not sure either. It's an extreme case. But it should probably work, even if it's not faster :)

**Comment by skaji** [comment]
Released https://metacpan.org/release/SKAJI/App-cpm-0.350
