### ISSUE TITLE
Support arbitrary location for cpanfile

### ISSUE THREAD

**Issue by oalders** [skaji/cpm#92]
`carton` allows me to `carton install --cpanfile path/to/cpanfile`, which is handy if I want to pull in dependencies from multiple projects.  Is this possible with `cpm`?  Based on the documentation, it doesn't appear to be.

**Comment by skaji** [comment]
yes:)

**Comment by oalders** [comment]
Ah, thanks.  Would you like a doc patch for this?

**Comment by skaji** [comment]
@oalders yes, please!

**Comment by oalders** [comment]
Thanks, @skaji!  I'm sorry I was slow about this.  I also didn't know about the snapshot path, so thanks for adding that as well.  :)
